name: CI

on:
  push:
    branches:
      - main
      - tests/wargaming
      - tests/routers

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm test